@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User as user
participant Mobile as mobile
participant Server as server
database Database as database

user -> mobile: Update User Request
activate mobile
mobile -> server: Send Update User Request
activate server
server -> database: Update User Info
    activate database

alt Update Successful
    database --> server: Update Successful
    deactivate database
    server --> mobile: Update Response (Success)
else Update Failed
    database --> server: Update Failed
    deactivate database
    server --> mobile: Update Response (Failure)
end
deactivate server

mobile -> user: Update Confirmation
deactivate mobile

@enduml