@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User as user
participant Mobile as mobile
participant Server as server
database Database as database

user -> mobile: View Student Info Request
activate mobile
mobile -> server: Send View Student Info Request
activate server
server -> database: Query Student Info
activate database
database --> server: Return Student Info
deactivate database
server --> mobile: Return Student Info
deactivate server
mobile --> user: Display Student Info
deactivate mobile

@enduml