spring.application.name=mydut-backend
######################################################################
# Jackson config
######################################################################
spring.jackson.time-zone=${app.config.timezone}
######################################################################
# Kafka config
######################################################################
spring.kafka.bootstrap-servers=${app.kafka.host}:${app.kafka.port}
spring.kafka.consumer.group-id=${app.profile}-${spring.application.name}
######################################################################
# Email properties
######################################################################
smtp.mail.host=${app.mail.host}
smtp.mail.port=${app.mail.port}
smtp.mail.username=${app.mail.username}
smtp.mail.password=${app.mail.password}
smtp.mail.auth=${app.mail.auth}
smtp.mail.ssl=${app.mail.ssl}
smtp.mail.starttls=${app.mail.starttls}

