package com.capstoneproject.mydut.common.enums;

/**
 * @author vndat00
 * @since 5/9/2024
 */
public enum ErrorCode {
    REQUEST_METHOD_NOT_SUPPORT,
    INVALID_VALUE,
    REQUIRED_FIELD_MISSING,
    BAD_REQUEST,
    INTERNAL_ERROR,
    NOT_FOUND,

    NOT_NULL,


    // Internal

    RESOURCE_NOT_FOUND,
    NOT_EMPTY,
    DATE_FORMAT_INVALID,
    VALIDATE_FAILURE,
    DISCOUNT_EXPIRED,
    ALREADY_EXIST,
    EMAIL_INVALID,
    UNAUTHORIZED,
    AUTHENTICATION_FAILURE,
    ACCESS_DENIED,
    TOKEN_EXPIRED,
    IO_ERROR,
    TOO_LONG,
    TOO_SHORT,
    OUTSIDE_REGISTRATION_PERIOD,
    ENOUGH_QUANTITY,
    ACTIVITY_GOING_ON
}
